server:
  port:
    8091

telegram:
  token: ${GEOGUESSR_TELEGRAM_TOKEN}
  chat-id: ${GEOGUESSR_TELEGRAM_CHAT_ID}
  bot-name: ${GEOGUESSR_TELEGRAM_BOT_NAME}

geoguessr:
  token: ${GEOGUESSR_TOKEN}
  baseUrl: https://www.geoguessr.com/api
  loginUrl: ${geoguessr.baseUrl}/v3/accounts/signin
  highScoresUrl: ${geoguessr.baseUrl}/v3/results/highscores
  challengesUrl: ${geoguessr.baseUrl}/v3/challenges
  defaultMapId: 648b198bb5790ced3d14e85c

spring:
  datasource:
    url: ${GEOGUESSR_DATA_SOURCE_URL:jdbc:postgresql://localhost:54323/geoguessr_data}
    username: ${GEOGUESSR_DATA_SOURCE_USERNAME:geoguessr_user}
    password: ${GEOGUESSR_DATA_SOURCE_PASSWORD:geoguessr}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update

